--------------------------------------------------------
--  File created - Wednesday-April-17-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADMINSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MMS"."ADMINSEQ"  MINVALUE 101 MAXVALUE 999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BRANCHADMINSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MMS"."BRANCHADMINSEQ"  MINVALUE 11 MAXVALUE 999 INCREMENT BY 1 START WITH 111 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "MMS"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEDICINEREQUESTID
--------------------------------------------------------

   CREATE SEQUENCE  "MMS"."MEDICINEREQUESTID"  MINVALUE 11 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 127 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEDICINESEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MMS"."MEDICINESEQ"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "MMS"."ADMIN" 
   (	"ADMINID" VARCHAR2(10 BYTE) DEFAULT 1, 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"AGE" NUMBER(2,0), 
	"GENDER" VARCHAR2(20 BYTE), 
	"DOB" VARCHAR2(10 BYTE), 
	"CONTACT_NUMBER" NUMBER(10,0), 
	"ALT_CONTACT_NUMBER" NUMBER(10,0), 
	"EMAIL_ID" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BRANCH_ADMIN
--------------------------------------------------------

  CREATE TABLE "MMS"."BRANCH_ADMIN" 
   (	"BRANCH_ADMIN_ID" VARCHAR2(100 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"AGE" NUMBER(2,0), 
	"GENDER" VARCHAR2(20 BYTE), 
	"DOB" VARCHAR2(10 BYTE), 
	"CONTACT_NUMBER" VARCHAR2(10 BYTE), 
	"ALT_CONTACT_NUMBER" VARCHAR2(10 BYTE), 
	"EMAIL_ID" VARCHAR2(50 BYTE), 
	"BRANCH_NAME" VARCHAR2(50 BYTE), 
	"ADDRESS_LINE_1" VARCHAR2(100 BYTE), 
	"ADDRESS_LINE_2" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(50 BYTE), 
	"ZIP_CODE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BRANCH_ADMIN_REQUEST
--------------------------------------------------------

  CREATE TABLE "MMS"."BRANCH_ADMIN_REQUEST" 
   (	"REQUEST_ID" NUMBER(8,0), 
	"BRANCH_ADMIN_ID" VARCHAR2(10 BYTE), 
	"REQUEST_DATE" VARCHAR2(200 BYTE), 
	"MEDICINE_ID_1" NUMBER DEFAULT 0, 
	"QUANTITY1" NUMBER(3,0) DEFAULT 0, 
	"MEDICINE_ID_2" NUMBER DEFAULT 0, 
	"QUANTITY2" NUMBER(3,0) DEFAULT 0, 
	"MEDICINE_ID_3" NUMBER DEFAULT 0, 
	"QUANTITY3" NUMBER(3,0) DEFAULT 0, 
	"MEDICINE_ID_4" NUMBER DEFAULT 0, 
	"QUANTITY4" NUMBER(3,0) DEFAULT 0, 
	"MEDICINE_ID_5" NUMBER DEFAULT 0, 
	"QUANTITY5" NUMBER(3,0) DEFAULT 0, 
	"OTHER_INFO" VARCHAR2(200 BYTE), 
	"ADMIN_PROCESS_DATE" VARCHAR2(20 BYTE), 
	"ADMIN_RESPONSE" VARCHAR2(1 BYTE) DEFAULT 'P', 
	"ADMIN_REMARKS" VARCHAR2(300 BYTE), 
	"REQUES_DATE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICINE
--------------------------------------------------------

  CREATE TABLE "MMS"."MEDICINE" 
   (	"MEDICINE_ID" NUMBER(8,0), 
	"MEDICINE_DESCRIPTION" VARCHAR2(200 BYTE), 
	"CURE_FOR" VARCHAR2(100 BYTE), 
	"MANUFACTURING_COMPANY" VARCHAR2(50 BYTE), 
	"DOSAGE" NUMBER(3,0), 
	"PRESCRIBED_FOR" VARCHAR2(1 BYTE), 
	"QUANTITY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REQUESTRESPONSETRIGGERTABLE
--------------------------------------------------------

  CREATE TABLE "MMS"."REQUESTRESPONSETRIGGERTABLE" 
   (	"PENDING" NUMBER DEFAULT 0, 
	"APPROVED" NUMBER DEFAULT 0, 
	"SRNO" VARCHAR2(20 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MMS.ADMIN
SET DEFINE OFF;
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin141','Demo','one',0,'male','2001-09-27',1234567890,7410258963,'a@gmail.com','abcd');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin142','adminFname','adminLastName',0,'M','21/11/7895',456140589,8912300,'faltubt@gmil.cm','50820');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin143','adminFname','adminLastName',0,'M','21/11/7895',4561240589,891230200,'fal@gmail.com','50820');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin1','sdsds','sdsds',22,'Male','11/02/2018',23232,2323,'ssdsds','abc');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin140','Nitin','Verma',0,'male','1997-08-15',9101010101,9191919191,'nitin@gmail.com','aarav');
REM INSERTING into MMS.BRANCH_ADMIN
SET DEFINE OFF;
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch1','sad','mad',55,'M','45/8/12','80258963','152630879','admin@gmail.com','Bname','ALine1','ALine2','City','State',102102);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch93','Payush','Bathla',23,'male','1996-08-20','4535934593','4390593453','payush@gmail.com','ENT','landran',null,' Abohar ','Punjab',152116);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch94','Rahul','Bajaj',22,'male','1997-02-16','3453457345','5645645645','rahul@gmail.com','Physiotherapy','Landran',null,' Ferozepur ','Punjab',123342);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch95','Nitin','Verma',23,'male','1996-09-10','8657656767','8956893569','nitin.balak@gmail.com','Dermatology','Foy Sagar',null,' Ajmer ','Rajasthan',305204);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch96','Sarth','Sharma',23,'male','1996-09-18','9565456456','9456975765','sarth@gmail.com','Cardiac','Landran',null,' Gangapur ','Rajasthan',546457);
REM INSERTING into MMS.BRANCH_ADMIN_REQUEST
SET DEFINE OFF;
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (115,'branch1','04/17/2019',101,2,101,0,101,0,101,0,101,0,null,null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (116,'branch1','04/17/2019',101,50,101,0,101,0,101,0,101,0,null,null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (118,'branch93','04/17/2019',101,45,101,0,101,0,101,0,101,0,null,null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (119,'branch94','04/17/2019',103,45,101,0,101,0,101,0,101,0,null,null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (120,'branch93','04/17/2019',102,20,101,0,101,0,101,0,101,0,null,null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (121,'branch93','04/17/2019',106,450,101,0,101,0,101,0,101,0,null,null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (122,'branch1','04/17/2019',101,455,101,0,101,0,101,0,101,0,null,null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (123,'branch1','04/17/2019',101,455,101,0,101,0,101,0,101,0,null,null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (124,'branch93','04/17/2019',103,45,101,0,101,0,101,0,101,0,'demo',null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (125,'branch93','04/17/2019',103,45,101,0,101,0,101,0,101,0,'demo',null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (126,'branch94','04/17/2019',101,45,101,0,101,0,101,0,101,0,'demoone',null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (113,'branch94','04/17/2019',102,12,101,0,101,0,101,0,101,0,'Required Urgent',null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (114,'branch94','04/17/2019',102,65,101,0,101,0,101,0,101,0,'try',null,'P',null,null);
REM INSERTING into MMS.MEDICINE
SET DEFINE OFF;
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (103,'Beneficial for migrain','Headache','cipla',150,'A',80);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (104,'Benefcial for bacterial infection caused in stomach by pyrolli bacteria','Bacterial Infection ','cipla',400,'A',150);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (105,'Beneficial for Stomach Ache','Stomach Pain','Cipla',50,'A',250);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (106,'Acyclovir Beneficial for Chicken Pox','Relieves Chicken pox effect','Mankind',500,'A',120);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (101,'Pacroma 400','Vitiligo','cipla',400,'A',30);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (102,'Bajaj','Cough','CDC',450,'A',120);
REM INSERTING into MMS.REQUESTRESPONSETRIGGERTABLE
SET DEFINE OFF;
Insert into MMS.REQUESTRESPONSETRIGGERTABLE (PENDING,APPROVED,SRNO) values (13,0,'1');
--------------------------------------------------------
--  DDL for Index BRANCH_ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MMS"."BRANCH_ADMIN_PK" ON "MMS"."BRANCH_ADMIN" ("BRANCH_ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEDICINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MMS"."MEDICINE_PK" ON "MMS"."MEDICINE" ("MEDICINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REQUESTRESPONSETRIGGERTABL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MMS"."REQUESTRESPONSETRIGGERTABL_PK" ON "MMS"."REQUESTRESPONSETRIGGERTABLE" ("SRNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MMS"."TABLE1_PK" ON "MMS"."ADMIN" ("ADMINID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "MMS"."ADMIN" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ADMINID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MMS"."ADMIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("EMAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("CONTACT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("ADMINID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BRANCH_ADMIN
--------------------------------------------------------

  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("ZIP_CODE" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("ADDRESS_LINE_1" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("BRANCH_NAME" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("EMAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("CONTACT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" ADD CONSTRAINT "BRANCH_ADMIN_PK" PRIMARY KEY ("BRANCH_ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("BRANCH_ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BRANCH_ADMIN_REQUEST
--------------------------------------------------------

  ALTER TABLE "MMS"."BRANCH_ADMIN_REQUEST" MODIFY ("QUANTITY1" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN_REQUEST" MODIFY ("MEDICINE_ID_1" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN_REQUEST" MODIFY ("REQUEST_DATE" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN_REQUEST" MODIFY ("BRANCH_ADMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN_REQUEST" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICINE
--------------------------------------------------------

  ALTER TABLE "MMS"."MEDICINE" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "MMS"."MEDICINE" ADD CONSTRAINT "MEDICINE_PK" PRIMARY KEY ("MEDICINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MMS"."MEDICINE" MODIFY ("PRESCRIBED_FOR" NOT NULL ENABLE);
  ALTER TABLE "MMS"."MEDICINE" MODIFY ("DOSAGE" NOT NULL ENABLE);
  ALTER TABLE "MMS"."MEDICINE" MODIFY ("MANUFACTURING_COMPANY" NOT NULL ENABLE);
  ALTER TABLE "MMS"."MEDICINE" MODIFY ("CURE_FOR" NOT NULL ENABLE);
  ALTER TABLE "MMS"."MEDICINE" MODIFY ("MEDICINE_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "MMS"."MEDICINE" MODIFY ("MEDICINE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REQUESTRESPONSETRIGGERTABLE
--------------------------------------------------------

  ALTER TABLE "MMS"."REQUESTRESPONSETRIGGERTABLE" ADD CONSTRAINT "REQUESTRESPONSETRIGGERTABL_PK" PRIMARY KEY ("SRNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MMS"."REQUESTRESPONSETRIGGERTABLE" MODIFY ("SRNO" NOT NULL ENABLE);
  ALTER TABLE "MMS"."REQUESTRESPONSETRIGGERTABLE" MODIFY ("APPROVED" NOT NULL ENABLE);
  ALTER TABLE "MMS"."REQUESTRESPONSETRIGGERTABLE" MODIFY ("PENDING" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger REQUESTTRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MMS"."REQUESTTRIGGER" 
AFTER INSERT OR UPDATE OF ADMIN_RESPONSE,REQUEST_ID ON BRANCH_ADMIN_REQUEST 
BEGIN
  update REQUESTRESPONSETRIGGERTABLE set APPROVED=(SELECT COUNT(REQUEST_ID) FROM BRANCH_ADMIN_REQUEST WHERE BRANCH_ADMIN_REQUEST.ADMIN_RESPONSE='A')WHERE SRNO=1 ;
  update REQUESTRESPONSETRIGGERTABLE set PENDING=(SELECT COUNT(REQUEST_ID) FROM BRANCH_ADMIN_REQUEST WHERE BRANCH_ADMIN_REQUEST.ADMIN_RESPONSE='P')WHERE SRNO=1 ;

END;
/
ALTER TRIGGER "MMS"."REQUESTTRIGGER" ENABLE;
